[package]
name = "shell"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.45"
clap = { version = "4.6.6", features = ["derive", "wrap_help"] }
codespan-reporting = "0.11.1"
hyprland = { version = "0.4.0-beta.3", default-features = false, features = ["data", "listener", "tokio"] }
iced = { git = "https://github.com/pop-os/iced", version = "0.14.0", default-features = false, features = ["image", "tokio", "wayland", "wgpu", "winit"] }
numbat = { version = "=1.16.0", default-features = false, features = ["fetch-exchangerates"] } # TODO Update once pop-osi/iced update wgpu to version 29
pipewire = "0.10.0"
rand = "0.10.2"
serde_json = "1.0.151"
signal-hook = { version = "0.4.4", default-features = false }
signal-hook-tokio = { version = "0.4.0", features = ["futures-v0_3"] }
smithay-client-toolkit = "0.20.0"
tokio = "1.53.1"
tokio-stream = "0.1.19"
zbus = { version = "5.19.0", default-features = false, features = ["blocking-api", "tokio"] }

[build-dependencies]
iced_lucide = "0.1.0"

[features]
debug = ["iced/debug"]
