module = "icon"

[icons]
wifi_off = "wifi-off"
wifi_1 = "wifi-zero"
wifi_2 = "wifi-low"
wifi_3 = "wifi-high"
wifi_4 = "wifi"
battery_charging = "battery-charging"
battery_1 = "battery"
battery_2 = "battery-low"
battery_3 = "battery-medium"
battery_4 = "battery-full"
